### ISSUE TITLE
npm安装后有history包

### ISSUE THREAD

**Issue by snadn** [react-component/queue-anim#11]
![qq 20160318095757](https://cloud.githubusercontent.com/assets/1269858/13866404/edd7e5fe-ecef-11e5-9de4-c44ab8cef208.png)

然后发现是原包里面就带着的

![qq 20160318095251](https://cloud.githubusercontent.com/assets/1269858/13866413/0f266816-ecf0-11e5-90ab-7e558a9f8117.png)

然后其他的几个组件也有这个问题

**Comment by afc163** [comment]
实测没有这个问题，检查下本地的 npm 环境吧。

**Comment by snadn** [comment]
npm 版本 2.14.12

可以下载 http://registry.npm.taobao.org/rc-queue-anim/download/rc-queue-anim-0.11.5.tgz 观察。里面有node_modules 目录。这个目录不应该出现在npm包里面吧。

**Comment by afc163** [comment]
确实有，很奇怪，这里是指定了 files 字段的，可能是 npm 的某个 bug：

https://github.com/react-component/queue-anim/blob/22a8fa91fdb1cacaaf7041c436f18aec1f628c9d/package.json#L20-L23

重新发了个 0.11.6。
