### ISSUE TITLE
warning use React.forwardRef()?

### ISSUE THREAD

**Issue by HuiGeGeGitHub** [react-component/queue-anim#113]
warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `TweenOne`.
`
<QueueAnim
                className="animWrap"
                key="local"
                delay={100}
                interval={50}
                type={["right", "left"]}
                ease={["easeOutQuart", null]}>
                    {
                        local.list.map((v, i) => <MediaItem
                            index={i}
                            item={v}
                           key={v.id}/>)
                    }
            </QueueAnim>
`

**Comment by Ancinek** [comment]
Having the same problem. Any idea how to fix this?

**Comment by neilveil** [comment]
I am also facing the same issue

**Comment by neilveil** [comment]
Just wrap your `MediaItem` component in a `div` & it will work like a charm

```jsx
<QueueAnim className="animWrap" key="local" delay={100} interval={50} type={["right", "left"]} ease={["easeOutQuart", null]}>
    { local.list.map((v, i) =><div key={v.id}><MediaItem index={i} item={v} /></div>) }
</QueueAnim>
```

**Comment by HuiGeGeGitHub** [comment]
> Just wrap your `MediaItem` component in a `div` & it will work like a charm
> It run well, Thanks
