### ISSUE TITLE
离场变成进场

### ISSUE THREAD

**Issue by visionchang** [react-component/queue-anim#119]
我复制的官网demo
remove 的时候反倒会 add

[![Edit youthful-lovelace-dd80n](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/youthful-lovelace-dd80n?fontsize=14&hidenavigation=1&theme=dark)

**Comment by visionchang** [comment]
我换成1.7.0版本就没问题了

**Comment by jljsj33** [comment]
StrictMode 模式下有鬼
