### ISSUE TITLE
How can I stop the animation?

### ISSUE THREAD

**Issue by tomaswitek** [react-component/queue-anim#131]
I use Ant's [List](https://ant.design/components/list/) component to render a list of jobs. Sometimes if job's status is changed it's removed from or added to a list. Which seems like a perfect use case for Queue Anim. I would like to animate those use cases.

It was quite straight forward to implement it using Queue Anim. Big kudoos to the team 🙌 
Here is a code snippet:
```
      import { List, Empty, Skeleton, Input } from 'antd';
      import QueueAnim from 'rc-queue-anim';

      <QueueAnim
        type="scaleX"
        component={List}
        paused
        componentProps={{
          loading,
          bordered: true,
          header: (
            <Input
              prefix={<Icon icon="filter" color="#ccc" />}
              placeholder={`Filter ${title} Jobs`}
              onChange={onInputChange}
            />
          ),
        }}
      >
        {jobs.length ? (
          jobs.map((job, key) => (
            <JobItem job={job} key={job.id} />
          ))
        ) : (
          <Empty style={{ marginTop: '40%' }} />
        )}
      </QueueAnim>
```

I would like to use those animations **only** when job status is updated, but the list is now animated every time the component is rerendered. 

There are use cases when I do not want to animate at all:
- inital render
- filtering the list
- navigating from a detail back to the list 

I didn't find a way how could I disable or pause the animation in those use cases 😢 
Should I render the list without `QueueAnim` component in those use cases? I don't think this will help and neither `appear` prop does.
Did I miss something?

**Comment by tomaswitek** [comment]
I could hack it with following props:

```
  animProps: {
    opacity: [1, 1],
    translateX: [0, 0],
  },
  duration: 0,
  interval: 0,
  appear: false,
```

But is this really the way to go?

**Comment by jljsj33** [comment]
animConfig={(e) => {}},, http://react-component.github.io/queue-anim/examples/param-func.html
