### ISSUE TITLE
无法成功显示出场效果

### ISSUE THREAD

**Issue by ChenLi0830** [react-component/queue-anim#14]
我参考了motion.ant.design上的例子，用bool state控制是否显示，但当state为false时，没有出场动画，而是瞬间消失。把各个例子都尝试了，仍然没有成功，请问可能是什么原因呢？
版本：
"antd": "^1.1.0",
"react": "^15.0.1",
"rc-queue-anim": "^0.11.9",

```
  getInitialState(){
    return {
      show:true,
      items: [{
        children: '依次进入1',
        key: 1,
      }, {
        children: '依次进入2',
        key: 2,
      }, {
        children: '依次进入3',
        key: 3,
      }],
    }
  },
```

```
<QueueAnim leaveReverse>
              {this.state.show ? this.state.items.map((item) => <div key={item.key}>
                {item.children}
              </div>) : null}
            </QueueAnim>
```

**Comment by jljsj33** [comment]
看代码没错啊。。。怎么操作的？？？？

**Comment by ChenLi0830** [comment]
谢谢回复哈，貌似找到原因了，我用了一个anchor的onClick来修改state，如下：
`<a href="#" onClick={this.toggle}>更多</a>`
删掉里面的**href**后，动画就正常了：
`<a onClick={this.toggle}>更多</a>`
Issue已经可以close了，但是还是好奇具体是为什么，有没有大牛可以解释一下？

**Comment by afc163** [comment]
用了 react-router ，发生了页面跳转吧。

**Comment by ChenLi0830** [comment]
@afc163 对，是用了react-router，不过跳转在浏览器导航栏里没有明显显示出来。

**Comment by ChenLi0830** [comment]
不管怎样，问题已经解决了，感谢帮忙！ @afc163 @jljsj33
