### ISSUE TITLE
是否可以支持自定义贝塞尔曲线参数？

### ISSUE THREAD

**Issue by zcmyworld** [react-component/queue-anim#25]
在 API 文档中，ease 这个属性支持 array 和 string 。

而 array 是形如 ['easeOutQuart', 'easeInOutQuart'] 这样的，将已定义的贝塞尔参数名称传进去。

请问，是否支持形如 [.42,0,.58,1] 这样形式的参数来定义运行的曲线？

如果不支持，请问有什么其他方案可以自定义吗？

感谢！

**Comment by afc163** [comment]
`ease={[.42,0,.58,1]}`

`ease={[[.42,0,.58,1], [.42,0,.58,1]]}`

应该都是支持的。

**Comment by zcmyworld** [comment]
我在不同的块中使用 ease={[.59,.21,.61,1.43]} 和 ease={[0,0,1,1]} 得出的都是同一个运行轨迹。
同时也不是该参数所定义的轨迹。

**Comment by zcmyworld** [comment]
我在不同的块中使用 ease={[.59,.21,.61,1.43]} 和 ease={[0,0,1,1]} 得出的都是同一个运行轨迹。
同时也不是该参数所定义的轨迹。版本是：0.12.5

**Comment by afc163** [comment]
应该是一个问题，你可以先试试：

```
ease={() => [.42,0,.58,1]}

ease={() => [[.42,0,.58,1], [.42,0,.58,1]]}
```

**Comment by afc163** [comment]
楼上的方法貌似也不行。

**Comment by zcmyworld** [comment]
使用ease={() => [.42,0,.58,1]}也不行。
我查看源代码发现，在最后使用velocity的时候通过getVelocityEasing方法来获取配置，
但是不管按照ease={() => [.42,0,.58,1]}或者ease={[.59,.21,.61,1.43]}这样的方式来调用，这个函数返回的都是 undefined
![image](https://cloud.githubusercontent.com/assets/8221626/20460943/7535719c-af2d-11e6-81e8-a892890f729d.png)
