### ISSUE TITLE
如何配置无离场动画效果

### ISSUE THREAD

**Issue by Caldis** [react-component/queue-anim#29]
目前的API, type和animConfig参数只能传字符串或数组, 我尝试了一下只能配置出:
1. 同时呈现相同的进出场动画
2. 同时呈现不同的进出场动画

是否有方法单独配置仅出现离场动画, 而不呈现出场动画.
或仅出现出场动画, 无离场动画的效果?

**Comment by jljsj33** [comment]
何必呢。。。
配置时间就可以了。。。不需要配置参数 
```jsx
<QueueAnim interval={[100, 0]} duration={[450, 0]} >
  <p key="1" />
  <p key="2" />
<QueueAnim>
```

**Comment by Caldis** [comment]
感谢...
