### ISSUE TITLE
[需求] 建议 type 类型增加一个 fade

### ISSUE THREAD

**Issue by Caldis** [react-component/queue-anim#30]
感觉是比较常用的几个动画之一. 不位移, 仅渐变, 建议可以加进默认的几个动画内.;

虽然直接用 animConfig 可以做到, 不过每次要写一遍也挺麻烦.

**Comment by jljsj33** [comment]
alpha

**Comment by jljsj33** [comment]
https://github.com/react-component/queue-anim/blob/master/src/animTypes.js#L18

**Comment by jljsj33** [comment]
如果多个用到同一个动画，，你可以自定义写。。。
```jsx
impurt animTypes form 'rc-queue-anim/lib/animTypes';
animType.xxx= { xxx: xx };
```

**Comment by Caldis** [comment]
感谢, 我是在: https://motion.ant.design/api/queue-anim 这里查, 里面没写出来, 可以顺便更新下嘿

**Comment by jljsj33** [comment]
好的。。谢谢。。
