### ISSUE TITLE
npm发布的最新版本不兼容react@15.5.4

### ISSUE THREAD

**Issue by zj1926** [react-component/queue-anim#36]
你好，
react从15.5.4开始不鼓励自带的propType了。
我注意到queue-anim的jsx源码已经用到了独立的prop-types包, 但是我npm下载到的最新的js文件里面还是引用的react.PropTypes(node_modules/rc-queue-anim/lib/QueueAnim.js, line number: 478)
不知道是否可以更新npm publish.

谢谢！

<img width="980" alt="screen shot 2017-05-20 at 8 34 24 am" src="https://cloud.githubusercontent.com/assets/5487482/26275789/37855888-3d37-11e7-8066-5ed419d26041.png">

**Comment by jljsj33** [comment]
好吧，，忘了这了。。。1.0.1 有 bug 我回退了。。。
