### ISSUE TITLE
还是和antd-mobile的搭配问题。

### ISSUE THREAD

**Issue by lmrwork** [react-component/queue-anim#37]
antd-mobile + react-router-dom 4.0 出现画面拉扯的现象。
能有它们搭配的文档就好了。

**Comment by jljsj33** [comment]
这是 web 版的，，mobile 最好用 rc-animate，queue-anim 在无线端运行的效率有点不好。。。

**Comment by lmrwork** [comment]
= =，velocity-animate效率更高，我又用回0.13.3了。。

**Comment by jljsj33** [comment]
有对比图吗？？ 在 web 下性能差不多。。。

**Comment by jljsj33** [comment]
ant motion 下用 twee-one-group 切换页面跟 velocity-animate 切换时的性能对比了下性能差不多。。。

**Comment by jljsj33** [comment]
无线端写动画尽量用 transform。。。动及 layout 和 paint 的性能太差。。。可看下 css 触发结构 https://csstriggers.com/transform

**Comment by lmrwork** [comment]
hi，谢谢回复，
使用velocity-animate有两个原因：1.部分动画有时需要提前中断。2.公司内部测试，发现部分三星手机对transform的支持度很差（使用ReactCSStransitionGroup）。

**Comment by jljsj33** [comment]
开始的运行速度可能是这个原因。。。TweenOne 去获取了 getComputedStyle 。。这个开始吃性能比大。。。但是在运行之中应该没啥差别吧。。。

**Comment by jljsj33** [comment]
后期我优化下 tween-one。。。或者你也可以PR来帮忙忧化。。。 动画尽量用一个类。。。本来就是考虑在一个工程里用到多个动画组件，而调用了多个动画类，当初是为了减少代码量而去掉 velocity-animate 的 。。。
