### ISSUE TITLE
离开动画结束后，为什么删除子元素

### ISSUE THREAD

**Issue by EngsShi** [react-component/queue-anim#38]
原本默认是被子元素撑大的界面，因为离开动画结束后子元素被删除，导致界面变形。

离开之后能否不进行删除操作，由开发人员自行在onEnd事件中处理。

**Comment by jljsj33** [comment]
切换删除时你子级本来就是删除状态啊。。。你可以在外层设个 height 或 min-height。。

**Comment by EngsShi** [comment]
为什么不用 opacity: 0 这种比较没侵入式的方式，或者给一个可选开关。

强行设置高度这种做法太不优雅了。

**Comment by jljsj33** [comment]
设 opacity: 0 时问题挺多的。。如果子级还是 QueueAnim 时，子级在切换时就没了效果。。还有不同元素切换时的考虑。
详细可参考 [ReactCSStransitionGroup](https://facebook.github.io/react/docs/animation.html)

**Comment by EngsShi** [comment]
了解了，感谢
