### ISSUE TITLE
latest version 1.2.2 on the npm install failed

### ISSUE THREAD

**Issue by initialdmg** [react-component/queue-anim#43]
node: 8.4
npm: 5.3
os: win 7 x64

failed at postinstall stage, package: fsevents.

i switched to v1.1 and installed successfully.

npm log:

7212 silly postinstall rc-queue-anim@1.2.2
7213 info lifecycle rc-queue-anim@1.2.2~postinstall: rc-queue-anim@1.2.2
7214 verbose unlock done using C:\Users\Administrator\AppData\Roaming\npm-cache\_locks\staging-948eb1e4f981cfbe.lock for E:\souceCode\spring-breeze\node_modules\.staging
7215 verbose stack Error: EPERM: operation not permitted, lstat 'E:\souceCode\spring-breeze\node_modules\fsevents\node_modules\getpass\node_modules'
7216 verbose cwd E:\souceCode\spring-breeze
7217 verbose Windows_NT 6.1.7601
7218 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "rc-queue-anim" "-D" "--registry=https://registry.npm.taobao.org"
7219 verbose node v8.4.0
7220 verbose npm  v5.3.0
7221 error path E:\souceCode\spring-breeze\node_modules\fsevents\node_modules\getpass\node_modules
7222 error code EPERM
7223 error errno -4048
7224 error syscall lstat
7225 error Error: EPERM: operation not permitted, lstat 'E:\souceCode\spring-breeze\node_modules\fsevents\node_modules\getpass\node_modules'
7225 error  { Error: EPERM: operation not permitted, lstat 'E:\souceCode\spring-breeze\node_modules\fsevents\node_modules\getpass\node_modules'
7225 error   stack: 'Error: EPERM: operation not permitted, lstat \'E:\\souceCode\\spring-breeze\\node_modules\\fsevents\\node_modules\\getpass\\node_modules\'',
7225 error   errno: -4048,
7225 error   code: 'EPERM',
7225 error   syscall: 'lstat',
7225 error   path: 'E:\\souceCode\\spring-breeze\\node_modules\\fsevents\\node_modules\\getpass\\node_modules' }
7226 error Please try running this command again as root/Administrator.
7227 verbose exit [ -4048, true ]

PS: i did run the install commad  as admin

**Comment by jljsj33** [comment]
![image](https://user-images.githubusercontent.com/6802825/29756412-45ff0e34-8bd6-11e7-9dba-57aac8f7f791.png)

我这能装。。。试下先删掉看看 `rm -rf node_modules`

**Comment by initialdmg** [comment]
嗯 装上了。谢谢！我怀疑是我电脑上用的 npm v5.3 的问题，这个版本的 npm 的 fsevents 有 [bug](https://github.com/npm/npm/issues/17671). 我降级了 npm 到 5.0.3 貌似就好了。
