### ISSUE TITLE
关于transform对子元素的影响

### ISSUE THREAD

**Issue by programmer-yang** [react-component/queue-anim#46]
问题：
动画结束后会在动画元素上添加行内样式`opacity: 1; transform: translate(0px, 0px);`
`transform`的特性会导致子元素`z-index` `fixed` 等一些其他属性异常

目前解决方案：
在`onEnd`事件里手动移除行内样式

期望：
动画执行完毕后移除行内样式`opacity: 1; transform: translate(0px, 0px);`

**Comment by jljsj33** [comment]
不可能做移除的，如果参数是 `opacity: 1; transform: translate(30px, 0px);`,  这样移除了会导致导常。。还是在 onEnd 里自已手动移除吧。。。

**Comment by programmer-yang** [comment]
ok
