### ISSUE TITLE
该组件对react的生命周期执行顺序产生影响

### ISSUE THREAD

**Issue by YDJSZY** [react-component/queue-anim#47]
`<QueueAnim delay={300} className="queue-simple" animConfig={[
                    { opacity: [1, 0], translateY: [0, 50] },
                    { opacity: [1, 0], translateY: [0, -50] }
                  ]} onEnd={this.clearQueueAnimStyle}>
     <section className="content" key="animation"><child></child></section>
</QueueAnim>`
发现在子组件里的componentDidMount比父组件的componentDidMount晚执行。去掉delay={300}也是一样

**Comment by jljsj33** [comment]
QueueAnim 的原理是： 通过延时来渲染子组并执行动画。。所以子组件渲染肯定比 queue-anim 要晚的。。

**Comment by YDJSZY** [comment]
`export default class Page_a extends React.Component{
constructor(props) {
        super(props);
}

componentDidMount(){
consolel.log("parent")
}
render(){
return <QueueAnim delay={300} className="queue-simple" animConfig={[ { opacity: [1, 0], translateY: [0, 50] }, { opacity: [1, 0], translateY: [0, -50] } ]} onEnd={this.clearQueueAnimStyle}> <section className="content" key="animation"><child></child></section> </QueueAnim>
}
}`
child组件的componentDidMount会比上面那个parent晚执行。这个正常吗？但是这样会带来一些问题。

**Comment by jljsj33** [comment]
正常 ，，有什么 问题 ？？

**Comment by YDJSZY** [comment]
比如我在打印出parent的这个父组件componentDidMount里发起一个请求，而请求携带的参数是子组件传上来的。那这样就会导致我父组件发起请求时还没拿到子组件的参数了。

**Comment by jljsj33** [comment]
onEnd 后回调父组件接口，不要在 didMount 里发。。。
