### ISSUE TITLE
发现通过ajax获取来的数据会使动画无效

### ISSUE THREAD

**Issue by hazeFlame** [react-component/queue-anim#48]

**Comment by hazeFlame** [comment]
<QueueAnim>
                    {
                        items && items.map((v, key) => (
                        <Card key={key} >
                            <div className="custom-image">
                                <Link to={{
                                    pathname: `/user/${v.author.loginname}`,
                                }}>
                                    <Avatar title={v.author.loginname} src={v.author.avatar_url} />
                                </Link>
                                <div className="tag">
                                    <Gettags tag={v.tab} top={v.top} good={v.good} />
                                </div>
                                <div className="reply_count">
                                    <span title="回复数">{v.reply_count}</span>/<span title="阅读数">{v.visit_count}</span>
                                </div>
                            </div>
                            <div className="custom-card">
                                <Link to={{
                                    pathname: `/topics/${v.id}`
                                }}>
                                    <p title={v.title}>{v.title}</p>
                                </Link>
                            </div>
                        </Card>))
                    }
                </QueueAnim>
没有看到translateX:30这个动画

**Comment by jljsj33** [comment]
试试：
```jsx
<QueueAnim>
  {
    items && items.map((v, key) => (
      <div key={key}>
        <Card >
          <div className="custom-image">
            <Link to={{
              pathname: `/user/${v.author.loginname}`,
            }}>
              <Avatar title={v.author.loginname} src={v.author.avatar_url} />
            </Link>
            <div className="tag">
              <Gettags tag={v.tab} top={v.top} good={v.good} />
            </div>
            <div className="reply_count">
              <span title="回复数">{v.reply_count}</span>/<span title="阅读数">{v.visit_count}</span>
            </div>
          </div>
          <div className="custom-card">
            <Link to={{
              pathname: `/topics/${v.id}`
            }}>
              <p title={v.title}>{v.title}</p>
            </Link>
          </div>
        </Card>
      </div>))
  }
</QueueAnim>
```

**Comment by hazeFlame** [comment]
ok，谢谢了，我看到组件没有把动画覆盖掉呀，为什么会使动画无效

**Comment by hazeFlame** [comment]
componentWillReceiveProps从新渲染组件的时候可以使用动画嘛

**Comment by jljsj33** [comment]
componentWillReceiveProps 时切换了 children 或 key 发生变化才会触发动画。。

**Comment by hazeFlame** [comment]
现有的数据依次退场，新数据同时依次进场。。。

**Comment by jljsj33** [comment]
是的。。

**Comment by hazeFlame** [comment]
然后变乱了= =

**Comment by jljsj33** [comment]
http://react-component.github.io/queue-anim/examples/dynamic.html 看下这个 demo 吧
