### ISSUE TITLE
根据 #29 关闭出场动画后，原本该被出场删除的元素未被删除

### ISSUE THREAD

**Issue by nuintun** [react-component/queue-anim#56]
![a](https://user-images.githubusercontent.com/1730277/41273392-de0dd5fe-6e4b-11e8-90d8-c4003213b71f.png)

![b](https://user-images.githubusercontent.com/1730277/41273395-e194527a-6e4b-11e8-9a14-5e7accb7c357.png)

如图，数据是父组件 `ajax` 异步 `props` 过来的，都设置有唯一稳定的 `key`，请求后新数据入场，旧数据没被删除，`onEnd` 事件也没有旧数据的出场回调，如果不设置  `interval={[100, 0]} duration={[450, 0]}` 旧数据在动画完成后会被删除！

**Comment by jljsj33** [comment]
> 请求后新数据入场，旧数据没被删除，

没懂! 旧数据是还保留着的吗？

**Comment by jljsj33** [comment]
好的，我调试出来了，我看下什么问题。。。

**Comment by jljsj33** [comment]
1.6.2

**Comment by nuintun** [comment]
@jljsj33 不会消失的问题修复了，但是还有 BUG，我开个 issues 写 demo 你看看
