### ISSUE TITLE
出场时组件在DOM中的顺序被改变了

### ISSUE THREAD

**Issue by nuintun** [react-component/queue-anim#58]
先看图 

![_20180620112950](https://user-images.githubusercontent.com/1730277/41635781-4a1907c8-747d-11e8-8068-e8a148babcef.png)

代码中 `Clients` 组件在 `2` 号位置

![a](https://user-images.githubusercontent.com/1730277/41635621-52716d76-747c-11e8-9065-6f107eb7142f.gif)

当 `Clients` 出场的时候 `Clients` 跑到了最后。

**Comment by jljsj33** [comment]
多次刷新了？？？

**Comment by nuintun** [comment]
@jljsj33 跟踪了下，的确是多次刷新了~

**Comment by jljsj33** [comment]
我修了下，，你再测试下吧。。。。

**Comment by nuintun** [comment]
@jljsj33 等你 publish 上去后我测测

**Comment by jljsj33** [comment]
1.6.3

**Comment by nuintun** [comment]
@jljsj33 明天试试~
