### ISSUE TITLE
动画中如果触发更新，未更新的元素行为不正常

### ISSUE THREAD

**Issue by nuintun** [react-component/queue-anim#60]
![b](https://user-images.githubusercontent.com/1730277/41711807-88fd8e24-757b-11e8-83b6-e1e56c4589f0.gif)

一开始没注意，应该还是 #58 的问题~

**Comment by jljsj33** [comment]
提供下示例。。。怎么出来的？？？

**Comment by jljsj33** [comment]
我测了一下并没有问题...

**Comment by nuintun** [comment]
@jljsj33 等我抽时间整理个 demo

**Comment by nuintun** [comment]
@jljsj33 写了 `demo` 测试，发现不太好复现，等有时间我跟踪下。

[rc-queue-anim](https://codesandbox.io/s/6v0xlq538z)

这个测试 `demo` 复现了一个 `bug` (`3 号动画失效`)，
上面的这个问题可能是这个原因造成的，情况比较极端。
如果是这个原因，看样我的项目以后得抽时间优化下了:joy:
