### ISSUE TITLE
有计划支持vue版吗？

### ISSUE THREAD

**Issue by zhengguorong** [react-component/queue-anim#62]
我试图编写一个vue版本，但是由于内部逻辑过于复杂，未能成功，

**Comment by jljsj33** [comment]
别人写过了。。。http://okoala.github.io/vue-antd/#!/components/queue-anim

**Comment by zhengguorong** [comment]
@jljsj33 这个我也看过，但是是依赖'velocity-animate'的，也就是你以前代码的实现方式，我想有没不依赖模版的实现。
