### ISSUE TITLE
列表过滤出现 same key 报错

### ISSUE THREAD

**Issue by nuintun** [react-component/queue-anim#66]
先看图，根据条件列表过滤，搜索的时候因为会有相同的项结果炸了，而且以前多次 render 闪烁的问题又出现了。
![_20181113145201](https://user-images.githubusercontent.com/1730277/48396547-c6e60580-e755-11e8-82f0-da2f4d85ffea.png)
![_20181113145136](https://user-images.githubusercontent.com/1730277/48396550-c8173280-e755-11e8-83db-dd97d16355e5.png)

**Comment by jljsj33** [comment]
我看看，，最近没升级过啊，，就 tween-one 在 animation 为 null 时删除了原来的 tween...

**Comment by jljsj33** [comment]
key 相同了你看下你 cards 数组里的 id 是不是相同了，多次 render 的问题在你原来的老 demo 里没有出现。。你再提供下重现？？？https://codesandbox.io/s/157l91xn4

**Comment by nuintun** [comment]
@jljsj33 

复现了

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mz1825qk3y)

**Comment by jljsj33** [comment]
你这几个空 div 是干什么用的？？这几个空 div 导至排序计算不了，出现了重复，，
![image](https://user-images.githubusercontent.com/6802825/48473750-17339500-e834-11e8-83e9-0bf3676e4a61.png)

你可以在这几个空 div 的最前面一个加个 div 带 key 的固定 list 里的 dom 位置即可。。本来 QueueAnim 子级是必须带 key 的。。。
![image](https://user-images.githubusercontent.com/6802825/48473927-71345a80-e834-11e8-9dc6-e162f4813558.png)

**Comment by nuintun** [comment]
@jljsj33 `flex` 布局，对齐用的。

**Comment by jljsj33** [comment]
[![Edit rc-queue-anim](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/400l0l3l34)

我这看这样算正常吧？？？4个占位符加一个定位符，定位符在动画前期没出来时，启用占位符，定位符出现后只不过多了个占位符，没问题啊。。。

**Comment by nuintun** [comment]
@jljsj33 

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qk37229okj)

动画组件和自带 `transition` 的元素使用会有些问题，比如和 `antd` 的 `Card` 组件，想正常得在 `Card` 外面套一层 `div`，有没有其它好的解决办法？

**Comment by jljsj33** [comment]
1. 套一层 div 是最方便的办法，，，
2. 加 animatingClassName， 'queue-anim-entering' 和  'queue-anim-leaving'  里都加 transition: none
3. 或你去提个 pr ，，，把 card 的 transition: all去掉。好像没什么用。。
