### ISSUE TITLE
Logical error in QueueAnim.jsx

### ISSUE THREAD

**Issue by samlanning** [react-component/queue-anim#68]
Hey there.

I came across [an alert for this project on LGTM](https://lgtm.com/projects/g/react-component/queue-anim/alerts/?mode=tree&ruleFocus=9980081) when going through results in a number of projects:

https://github.com/react-component/queue-anim/blob/71facadc4030fd4838ce474d8f68542e78870e5d/src/QueueAnim.jsx#L401

This code looks incorrect, as the `!` operator binds more tightly than `>=`. The result is that the expression is interpreted as:

```ts
const paused = this.keysToEnterPaused[key] && (!this.keysToLeave.indexOf(key)) >= 0;
```
And as the result of `!this.keysToLeave.indexOf(key))` will be a boolean, and `true >= 0` and `false >= 0` both evaluate to true... this is equivalent to:

```ts
const paused = this.keysToEnterPaused[key] && true;
```
Which is equal to:
```ts
const paused = this.keysToEnterPaused[key];
```
I tried to determine what the expression that was meant here was, but from the comments and code, could not determine which of these was meant:
1. ```ts
   !(this.keysToLeave.indexOf(key) >= 0)
   ```
2. ```ts
   this.keysToLeave.indexOf(key) >= 0
   ```
If it was (1), it would probably be better to write it as `this.keysToLeave.indexOf(key) === -1`.

*(Full disclosure: I'm part of the team behind LGTM.com)*

**Comment by jljsj33** [comment]
Haha, I don't know how to write this way. The correct one should be `this.keysToLeave.indexOf(key) === -1`, but a little problem.
I will check first

**Comment by jljsj33** [comment]
1.6.9
