### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by Ehesp** [react-component/queue-anim#7]
Using QueueAnim & React Router, with the example: http://ant.design/components/queue-anim/#/anim-demo-router?_k=cs5hek

When navigating between routes quickly, if a previous animation hasn't finished yet and you switch route, the console warning appears:

Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

To reproduce: Open the example and open the console. Quickly switch between tabs and you'll see the error appear.

**Comment by jljsj33** [comment]
[pull#6](https://github.com/react-component/queue-anim/pull/6), fixes

**Comment by Ehesp** [comment]
Can we get that one merged? It fixes a couple of big bugs!

**Comment by afc163** [comment]
fixing

**Comment by afc163** [comment]
Fixed in `0.11.3`
