### ISSUE TITLE
rc-queue-anim引用问题

### ISSUE THREAD

**Issue by Suolm1** [react-component/queue-anim#79]
项目框架运用的是React。
在一个组件中引用rc-queue-anim，在配置webpack文件中的File-Loader时，如果加入obj的文件类型，会导致页面加载失败，页面会出现白屏的现象，在开发者工具中没有报错。我定位了一下，页面渲染到 import QueueAnim from 'rc-queue-anim' 时，就会停止渲染。
期待您的回复，谢谢。

![react组件中引用](https://user-images.githubusercontent.com/48901868/54898013-984b1900-4f05-11e9-9e86-99b21d6045a1.jpg)
![webpack中的配置](https://user-images.githubusercontent.com/48901868/54898025-9c773680-4f05-11e9-9d38-802cff11901e.jpg)

**Comment by jljsj33** [comment]
能否提供详细的演示？？？有点看不懂，，，file-loader 不可能跟组件冲突啊。。。

**Comment by Suolm1** [comment]
在file-loader上配置了obj文件类型，引入了rc-queue-anim，页面会白屏，不引入的话，页面就会正常加载。
白屏时的页面结构。
![image](https://user-images.githubusercontent.com/48901868/54904628-f1bd4300-4f19-11e9-891f-423299e402d8.png)

**Comment by jljsj33** [comment]
什么脚手架？？？？

**Comment by jljsj33** [comment]
把脚手架和 webpack 的配置贴上来，，，我这边看看能不能重现，，，没法重现，我也不知道啥问题。。。

**Comment by Suolm1** [comment]
没有用脚手架，自己写的，
![image](https://user-images.githubusercontent.com/48901868/54908151-32b95580-4f22-11e9-8bbb-b729fbb3369f.png)

**Comment by jljsj33** [comment]
你能抽一个能跑的 demo 发我邮箱吗？？

**Comment by Suolm1** [comment]
你好，请问发你哪个邮箱，今天我自己找了一个demo，复现了这种情况。

**Comment by Suolm1** [comment]
这次的demo,出现了一个报错。 
![image](https://user-images.githubusercontent.com/48901868/54982397-b8eaa000-4fe5-11e9-88e7-8371f18255f5.png)

**Comment by Suolm1** [comment]
两次出现的情况不一样，我看看能不能真正的复现我第一次遇到的情况。

**Comment by Suolm1** [comment]
问题已经解决了，是我自己的问题，file-loader的正则有问题。

**Comment by jljsj33** [comment]
好吧，，我刚看了下，，这样是可以的，，正想说你这句是有问题。。

```
{ test: /\.(glb|eot|woff|woff2|svg|ttf|otf)([\?]?.*)$/, use: 'file-loader' },
    { test: /\.obj$/, use: 'file-loader' },
    { test: /\.html$/, use: 'html-loader' },
```
