### ISSUE TITLE
为什么执行动画前key=“1”的组件会被渲染

### ISSUE THREAD

**Issue by Willworkgogogo** [react-component/queue-anim#86]
[![Edit 转场动画测试](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhuanchangdonghuaceshi-46619?fontsize=14)

组件1多渲染了一次
![image](https://user-images.githubusercontent.com/20815934/58266097-95f52600-7db3-11e9-9747-1bae5e4418dc.png)

**Comment by jljsj33** [comment]
你放三个, 就会渲染 3 次 comp1, 2次 comp2，，，children 是存在 queueAnim 的 state 里的，，每进入一个就会重新 render 一遍。。。

**Comment by Willworkgogogo** [comment]
如果组件中有http请求类的操作，将会多次请求，这种情况该怎么处理呢？

**Comment by jljsj33** [comment]
PureComponent

**Comment by jljsj33** [comment]
你在 render 里请求操作的？？？

**Comment by Willworkgogogo** [comment]
刚试验了，确实是我使用方式和理解的问题，一定是我使用的方式不对。谢谢指导 O(∩_∩)O
